# Generated by Django 5.2.5 on 2026-06-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('games', '0002_boardgames_gamedetails_delete_boardgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_games',
            field=models.ManyToManyField(blank=True, related_name='fans', to='games.boardgames'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='profiles/'),
        ),
    ]
