# Generated by Django 5.2.5 on 2026-06-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_favorite_games_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_game_tags',
            field=models.TextField(blank=True),
        ),
    ]
