# Generated by Django 5.2.5 on 2026-06-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_merge_0003_boardgames_view_count_0004_remove_recommendationfeedback_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='family_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='party_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
