# Generated by Django 5.2.5 on 2026-06-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_boardgames_family_rank_boardgames_party_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
