# Generated by Django 5.2.5 on 2026-06-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_boardgames_image_url_boardgames_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='boardlife_game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='boardlife_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='boardlife_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='korean_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
