# Generated by Django 5.2.5 on 2026-06-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_boardgames_boardlife_game_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('source', models.CharField(default='ai_bgg_context', max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boardgame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule_summary', to='games.boardgames')),
            ],
        ),
    ]
